[keyboard]
name = "rmk-palm"
product_name = "rmk-palm"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "TIS"
chip = "nrf52840"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true
rows = 5
cols = 12
layers = 4
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5)             (0,6) (0,7) (0,8) (0,9) (0,10) (0,11)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5)             (1,6) (1,7) (1,8) (1,9) (1,10) (1,11)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5)             (2,6) (2,7) (2,8) (2,9) (2,10) (2,11)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5)             (3,6) (3,7) (3,8) (3,9) (3,10) (3,11)
                        (4,0) (4,1) (4,2) (4,9) (4,10) (4,11)
"""

[aliases]
upper = "MO(upper)"
lower = "MO(lower)"
adjust = "MO(adjust)"
ctl_esc = "MT(esc, lctrl)"
tild = "SHIFTED(grv)"
exlm = "SHIFTED(1)"
at = "SHIFTED(2)"
hash = "SHIFTED(3)"
dlr = "SHIFTED(4)"
perc = "SHIFTED(5)"
circ = "SHIFTED(6)"
ampr = "SHIFTED(7)"
astr = "SHIFTED(8)"
lprn = "SHIFTED(9)"
rprn = "SHIFTED(0)"
unds = "SHIFTED(mins)"
plus = "SHIFTED(eql)"
lcbr = "SHIFTED(lbrc)"
rcbr = "SHIFTED(rbrc)"
coln = "SHIFTED(scln)"
pipe = "SHIFTED(bsls)"
bt0 = "User0"
bt1 = "User1"
bt2 = "User2"
btnext = "User3"
btprev = "User4"
btclr = "User5"
usbble = "User6"

[[layer]]
name = "base"
keys = """
grv 1 2 3 4 5 6 7 8 9 0 bspc
tab Q W E R T Y U I O P del
@ctl_esc A S D F G H J K L scln quot
lsft Z X C V B N M comm dot slsh rsft
@upper ent lgui lalt spc @lower
"""

[[layer]]
name = "upper"
keys = """
F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12
_ No lbrc @lcbr @rcbr No @circ @lprn @rprn rbrc @tild _
_ @exlm @at @hash @dlr @perc @ampr mins eql bsls grv _
_ lsft lctl lalt lgui No @astr @unds @plus @pipe slsh _
_ _ _ _ bspc @adjust
"""

[[layer]]
name = "lower"
keys = """
F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12
_ ins 1 2 3 mins home pgdn pgup end @coln _
_ del 4 5 6 dot left down up right scln _
_ caps 7 8 9 0 No rgui ralt rctl rsft _
tab esc _ _ _ _
"""

[[layer]]
name = "adjust"
keys = """
F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12
_ _ _ _ _ _ @bt0 @bt1 @bt2 @btclr @usbble _
_ _ _ _ _ _ mnxt vold volu mply _ _
_ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _
"""

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04"]
output_pins = ["P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04"]
output_pins = ["P0_09", "P0_10", "P1_11", "P1_13", "P1_15", "P0_02"]
